import { Component, ElementRef, Inject, OnInit, ViewChild } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialogRef, MatDialogConfig, MatDialog } from '@angular/material/dialog';
import { MatTableDataSource } from '@angular/material/table';
import { PlansService } from 'src/app/services/plans.service';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { VideoPlayerComponent } from '../video-player/video-player.component';

@Component({
  selector: 'app-view-plan',
  templateUrl: './view-plan.component.html',
  styleUrls: ['./view-plan.component.scss']
})


export class ViewPlanComponent implements OnInit {

  @ViewChild('table') table!: ElementRef;

  displayedColumns: string[] = [
    'plan_name',
    'plan_description',
    'weight',
    'squat',
    'bench',
    'deadlift',

  ];


  displayedColumns2: string[] = [

    'workout_name',
    'name',
    'sets',
    'reps',
    'rpe',
    'tempo',
    'description',
    'video_url'


  ];
  data: any

  dataSource: any

  dataToExcel1: any[] = []

  dataToExcel2: any[] = []

  workoutDataSource: any

  constructor(@Inject(MAT_DIALOG_DATA) public dialogData: any,

    private dialogRef: MatDialogRef<ViewPlanComponent>, private planService: PlansService, private dialog: MatDialog,
  ) {

  }
  openLink(link: string): void {
    const dialogConfig = new MatDialogConfig();
    dialogConfig.data = {
      link: link
    }

    this.dialog.open(VideoPlayerComponent, dialogConfig)
  }

  ngOnInit(): void {
    this.data = this.dialogData.data
    this.viewPlan(this.data.plan_id)

  }

  viewPlan(id: any): void {
    this.planService.generatePlan(id).subscribe((response: any) => {

      this.dataToExcel1 = [response]
      this.dataToExcel2 = response.workouts



      this.dataSource = new MatTableDataSource([response])
      this.workoutDataSource = new MatTableDataSource(response.workouts)

    })
  }









  generatePdf(): void {
    const element = document.getElementById('table');
    if (element) {
      const doc = new jsPDF('p', 'pt', 'a4');
      autoTable(doc, {
        didDrawCell: function (data) {
          if (data.section === 'head') {
            doc.setTextColor(0, 0, 0);
            doc.setFont('Helvetica', 'normal')
            doc.text('Plan generated by MaxYourLifts', 40, 20);
          }
        },
        html: '#table',

      });
      autoTable(doc, {

        html: '#table2',
        theme: 'striped',
        columns: [
          { dataKey: 0 },
          { dataKey: 1 },
          { dataKey: 2 },
          { dataKey: 3 },
          { dataKey: 4 },
          { dataKey: 5 }

        ],
        columnStyles: {
          0: {
            font: 'Montserrat',
          },
          1: {
            font: 'Montserrat',
          },

          2: {
            font: 'Montserrat',
          },
          3: {
            font: 'Montserrat',
          },
          4: {
            font: 'Montserrat',
          },
          5: {
            font: 'Montserrat',
          },

        },

      });
      doc.save(this.data.plan_name);
    }
  }




}


